name: Test & Build

on:
  workflow_call:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.event.pull_request.number || github.ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(vars.TESTABLE_PKGS) }}
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    env:
      ARTIFACTS_API_TOKEN: ${{ secrets.ARTIFACTS_API_TOKEN }}
      ARTIFACTS_USERNAME: ${{ secrets.ARTIFACTS_USERNAME }}
      ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      ARTIFACTS_CHARACTER: ${{ secrets.ARTIFACTS_CHARACTER }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6  # v2.2.0
        with:
          bun-version-file: ".bun-version"
      - run: bun install --frozen-lockfile
      - run: bun check
      - run: bun test

  build:
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(vars.BUILDABLE_PKGS) }}
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6  # v2.2.0
        with:
          bun-version-file: ".bun-version"
      - run: bun install --frozen-lockfile
      - run: bun run build
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: ${{ matrix.package }}-dist
          path: packages/${{ matrix.package }}/dist
          compression-level: 9
          retention-days: 7
